/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author meenalsarwaiya
 */
public class CompanyDashboard extends javax.swing.JFrame {

    /**
     * Creates new form CompanyDashboard
     */
    public CompanyDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnPortfolio = new javax.swing.JButton();
        btnPortfolio1 = new javax.swing.JButton();
        btnPortfolio2 = new javax.swing.JButton();
        btnPortfolio3 = new javax.swing.JButton();
        btnPortfolio4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnPortfolio.setBackground(new java.awt.Color(0, 0, 0));
        btnPortfolio.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnPortfolio.setForeground(new java.awt.Color(255, 255, 255));
        btnPortfolio.setText("Manage Equity Holder");
        btnPortfolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortfolioActionPerformed(evt);
            }
        });

        btnPortfolio1.setBackground(new java.awt.Color(0, 0, 0));
        btnPortfolio1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnPortfolio1.setForeground(new java.awt.Color(255, 255, 255));
        btnPortfolio1.setText("Stock Price");
        btnPortfolio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortfolio1ActionPerformed(evt);
            }
        });

        btnPortfolio2.setBackground(new java.awt.Color(0, 0, 0));
        btnPortfolio2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnPortfolio2.setForeground(new java.awt.Color(255, 255, 255));
        btnPortfolio2.setText("Schedule Meeting");
        btnPortfolio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortfolio2ActionPerformed(evt);
            }
        });

        btnPortfolio3.setBackground(new java.awt.Color(0, 0, 0));
        btnPortfolio3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnPortfolio3.setForeground(new java.awt.Color(255, 255, 255));
        btnPortfolio3.setText("Add Equirty Holder");
        btnPortfolio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortfolio3ActionPerformed(evt);
            }
        });

        btnPortfolio4.setBackground(new java.awt.Color(0, 0, 0));
        btnPortfolio4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnPortfolio4.setForeground(new java.awt.Color(255, 255, 255));
        btnPortfolio4.setText("Balance Sheet");
        btnPortfolio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortfolio4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPortfolio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPortfolio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPortfolio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPortfolio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPortfolio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnPortfolio3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPortfolio1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPortfolio4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPortfolio2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPortfolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortfolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPortfolioActionPerformed

    private void btnPortfolio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortfolio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPortfolio1ActionPerformed

    private void btnPortfolio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortfolio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPortfolio2ActionPerformed

    private void btnPortfolio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortfolio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPortfolio3ActionPerformed

    private void btnPortfolio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortfolio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPortfolio4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPortfolio;
    private javax.swing.JButton btnPortfolio1;
    private javax.swing.JButton btnPortfolio2;
    private javax.swing.JButton btnPortfolio3;
    private javax.swing.JButton btnPortfolio4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
