/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author apoorvakulkarni
 */
public class EquityHoldersPerksPanel extends javax.swing.JPanel {

    /**
     * Creates new form EquityHoldersPerksPanel
     */
    public EquityHoldersPerksPanel() {
        initComponents();
        
        jTextAreaNews.setText("Microsoft's products are mostly marketed to other businesses rather than consumers.\n But stockholders are given a passcode to enter a special retail store. Once inside, you'll find generous discounts\n of up to 25% on Thinkpad laptops and tablets and other merchandise.");

        jTextAreaNews1.setText("Shareholders get privileged rates well below sticker price.\\n In some cases, Apple products can be purchased for just 4% above employee pricing \nHere's what the company has to say:\n As a special thank-you to our shareholders, we offer qualifying shareholders"
        + " the opportunity to participate in our \"Friends & Neighbors\"\n Special Pricing Privilege "
        + "(also known as our \"X-Plan\")."
        );
        
        jTextAreaNews2.setText("You could log on to Expedia to book a hotel room at Holiday Inn or one of IHG's other resorts.\n But shareholders have special access to a private website with deeper (unpublished) discounts.\n Further details are available at the company's website.");
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNews = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNews1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaNews2 = new javax.swing.JTextArea();

        jTextAreaNews.setColumns(20);
        jTextAreaNews.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNews);

        jTextAreaNews1.setColumns(20);
        jTextAreaNews1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNews1);

        jTextAreaNews2.setColumns(20);
        jTextAreaNews2.setRows(5);
        jScrollPane3.setViewportView(jTextAreaNews2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaNews;
    private javax.swing.JTextArea jTextAreaNews1;
    private javax.swing.JTextArea jTextAreaNews2;
    // End of variables declaration//GEN-END:variables
}
